# Generated by Django 3.0.6 on 2020-05-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzatopping',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pizzasize', to='orders.PizzaSize'),
            preserve_default=False,
        ),
    ]
