# Generated by Django 3.0.6 on 2020-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200516_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizzatopping',
            name='base',
        ),
        migrations.AddField(
            model_name='pizza',
            name='base',
            field=models.ManyToManyField(related_name='pizzatopping', to='orders.PizzaBase'),
        ),
    ]
