# Generated by Django 3.0.6 on 2020-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatopping',
            name='number_of_toppings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
