# Generated by Django 3.0.6 on 2020-05-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pizzatopping_number_of_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzatopping',
            old_name='pizza_topping',
            new_name='topping_name',
        ),
    ]
