# Generated by Django 3.0.6 on 2020-05-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200526_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdOns',
        ),
    ]
