# Generated by Django 3.0.6 on 2020-05-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_addons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddOns',
            new_name='AddOn',
        ),
    ]
