# Generated by Django 3.0.6 on 2020-05-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200526_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='size',
        ),
    ]
