# Generated by Django 3.0.6 on 2020-05-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_dinnerplattername_pasta_salad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
