# Generated by Django 3.0.6 on 2020-05-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_recivedorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recivedorders',
            old_name='price',
            new_name='order_total',
        ),
    ]
