# Generated by Django 3.0.6 on 2020-05-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_recivedorders_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecivedOrders',
        ),
    ]
