# Generated by Django 3.0.6 on 2020-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_recivedorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecivedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=65)),
                ('all_items', models.TextField()),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='Ordered', max_length=65)),
            ],
        ),
    ]
