# Generated by Django 3.0.6 on 2020-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_pizzabase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplattername',
            name='dp_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pasta',
            name='pasta_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='salad',
            name='salad_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subname',
            name='sub_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
