# Generated by Django 3.0.6 on 2020-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200601_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='recivedorders',
            name='time',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='recivedorders',
            name='status',
            field=models.CharField(default='Preparing', max_length=65),
        ),
    ]
