# Generated by Django 3.0.6 on 2020-06-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200603_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='recivedorders',
            name='date',
            field=models.CharField(default='', max_length=65),
        ),
    ]
