# Generated by Django 3.0.6 on 2020-06-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20200603_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recivedorders',
            name='date',
            field=models.CharField(max_length=65),
        ),
    ]
